// Code generated by go-swagger; DO NOT EDIT.

package trader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateNewtraderHandlerFunc turns a function with the right signature into a create newtrader handler
type CreateNewtraderHandlerFunc func(CreateNewtraderParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateNewtraderHandlerFunc) Handle(params CreateNewtraderParams) middleware.Responder {
	return fn(params)
}

// CreateNewtraderHandler interface for that can handle valid create newtrader params
type CreateNewtraderHandler interface {
	Handle(CreateNewtraderParams) middleware.Responder
}

// NewCreateNewtrader creates a new http.Handler for the create newtrader operation
func NewCreateNewtrader(ctx *middleware.Context, handler CreateNewtraderHandler) *CreateNewtrader {
	return &CreateNewtrader{Context: ctx, Handler: handler}
}

/*CreateNewtrader swagger:route POST /trader/register trader createNewtrader

Creates new trader

*/
type CreateNewtrader struct {
	Context *middleware.Context
	Handler CreateNewtraderHandler
}

func (o *CreateNewtrader) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateNewtraderParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
