// Code generated by go-swagger; DO NOT EDIT.

package trader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateNewtraderOKCode is the HTTP code returned for type CreateNewtraderOK
const CreateNewtraderOKCode int = 200

/*CreateNewtraderOK susscefull operation

swagger:response createNewtraderOK
*/
type CreateNewtraderOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateNewtraderOK creates CreateNewtraderOK with default headers values
func NewCreateNewtraderOK() *CreateNewtraderOK {

	return &CreateNewtraderOK{}
}

// WithPayload adds the payload to the create newtrader o k response
func (o *CreateNewtraderOK) WithPayload(payload string) *CreateNewtraderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create newtrader o k response
func (o *CreateNewtraderOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewtraderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
