// Code generated by go-swagger; DO NOT EDIT.

package trader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "exchange/models"
)

// TraderPortfoliosOKCode is the HTTP code returned for type TraderPortfoliosOK
const TraderPortfoliosOKCode int = 200

/*TraderPortfoliosOK successful operation

swagger:response traderPortfoliosOK
*/
type TraderPortfoliosOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Portfolios `json:"body,omitempty"`
}

// NewTraderPortfoliosOK creates TraderPortfoliosOK with default headers values
func NewTraderPortfoliosOK() *TraderPortfoliosOK {

	return &TraderPortfoliosOK{}
}

// WithPayload adds the payload to the trader portfolios o k response
func (o *TraderPortfoliosOK) WithPayload(payload []*models.Portfolios) *TraderPortfoliosOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the trader portfolios o k response
func (o *TraderPortfoliosOK) SetPayload(payload []*models.Portfolios) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TraderPortfoliosOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Portfolios, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
