// Code generated by go-swagger; DO NOT EDIT.

package trader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TraderPortfolioHandlerFunc turns a function with the right signature into a trader portfolio handler
type TraderPortfolioHandlerFunc func(TraderPortfolioParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn TraderPortfolioHandlerFunc) Handle(params TraderPortfolioParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// TraderPortfolioHandler interface for that can handle valid trader portfolio params
type TraderPortfolioHandler interface {
	Handle(TraderPortfolioParams, interface{}) middleware.Responder
}

// NewTraderPortfolio creates a new http.Handler for the trader portfolio operation
func NewTraderPortfolio(ctx *middleware.Context, handler TraderPortfolioHandler) *TraderPortfolio {
	return &TraderPortfolio{Context: ctx, Handler: handler}
}

/*TraderPortfolio swagger:route GET /trader/portfolio trader traderPortfolio

Get trader current portfolio

*/
type TraderPortfolio struct {
	Context *middleware.Context
	Handler TraderPortfolioHandler
}

func (o *TraderPortfolio) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTraderPortfolioParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
