// Code generated by go-swagger; DO NOT EDIT.

package trader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTraderPortfoliosParams creates a new TraderPortfoliosParams object
// no default values defined in spec.
func NewTraderPortfoliosParams() TraderPortfoliosParams {

	return TraderPortfoliosParams{}
}

// TraderPortfoliosParams contains all the bound params for the trader portfolios operation
// typically these are obtained from a http.Request
//
// swagger:parameters traderPortfolios
type TraderPortfoliosParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Trader Identifier
	  Required: true
	  In: header
	*/
	Token string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTraderPortfoliosParams() beforehand.
func (o *TraderPortfoliosParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindToken(r.Header[http.CanonicalHeaderKey("token")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindToken binds and validates parameter Token from header.
func (o *TraderPortfoliosParams) bindToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("token", "header")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("token", "header", raw); err != nil {
		return err
	}

	o.Token = raw

	return nil
}
