// Code generated by go-swagger; DO NOT EDIT.

package trader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TraderPortfoliosHandlerFunc turns a function with the right signature into a trader portfolios handler
type TraderPortfoliosHandlerFunc func(TraderPortfoliosParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn TraderPortfoliosHandlerFunc) Handle(params TraderPortfoliosParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// TraderPortfoliosHandler interface for that can handle valid trader portfolios params
type TraderPortfoliosHandler interface {
	Handle(TraderPortfoliosParams, interface{}) middleware.Responder
}

// NewTraderPortfolios creates a new http.Handler for the trader portfolios operation
func NewTraderPortfolios(ctx *middleware.Context, handler TraderPortfoliosHandler) *TraderPortfolios {
	return &TraderPortfolios{Context: ctx, Handler: handler}
}

/*TraderPortfolios swagger:route GET /trader/portfolios trader traderPortfolios

Get all traders portfolios

*/
type TraderPortfolios struct {
	Context *middleware.Context
	Handler TraderPortfoliosHandler
}

func (o *TraderPortfolios) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTraderPortfoliosParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
