// Code generated by go-swagger; DO NOT EDIT.

package trader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "exchange/models"
)

// TraderPortfolioOKCode is the HTTP code returned for type TraderPortfolioOK
const TraderPortfolioOKCode int = 200

/*TraderPortfolioOK successful operation

swagger:response traderPortfolioOK
*/
type TraderPortfolioOK struct {

	/*
	  In: Body
	*/
	Payload models.Portfolio `json:"body,omitempty"`
}

// NewTraderPortfolioOK creates TraderPortfolioOK with default headers values
func NewTraderPortfolioOK() *TraderPortfolioOK {

	return &TraderPortfolioOK{}
}

// WithPayload adds the payload to the trader portfolio o k response
func (o *TraderPortfolioOK) WithPayload(payload models.Portfolio) *TraderPortfolioOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the trader portfolio o k response
func (o *TraderPortfolioOK) SetPayload(payload models.Portfolio) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TraderPortfolioOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Portfolio, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
