// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"exchange/restapi/operations/asset"
	"exchange/restapi/operations/order"
	"exchange/restapi/operations/trader"
)

// NewExchangeAppAPI creates a new ExchangeApp instance
func NewExchangeAppAPI(spec *loads.Document) *ExchangeAppAPI {
	return &ExchangeAppAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		UrlformConsumer:     runtime.DiscardConsumer,
		JSONProducer:        runtime.JSONProducer(),
		AssetAssetListHandler: asset.AssetListHandlerFunc(func(params asset.AssetListParams) middleware.Responder {
			return middleware.NotImplemented("operation AssetAssetList has not yet been implemented")
		}),
		TraderCreateNewtraderHandler: trader.CreateNewtraderHandlerFunc(func(params trader.CreateNewtraderParams) middleware.Responder {
			return middleware.NotImplemented("operation TraderCreateNewtrader has not yet been implemented")
		}),
		OrderProcessOrderHandler: order.ProcessOrderHandlerFunc(func(params order.ProcessOrderParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation OrderProcessOrder has not yet been implemented")
		}),
		TraderTraderPortfolioHandler: trader.TraderPortfolioHandlerFunc(func(params trader.TraderPortfolioParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation TraderTraderPortfolio has not yet been implemented")
		}),
		TraderTraderPortfoliosHandler: trader.TraderPortfoliosHandlerFunc(func(params trader.TraderPortfoliosParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation TraderTraderPortfolios has not yet been implemented")
		}),

		// Applies when the "X-TOKEN" header is set
		AccessTokenAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (accessToken) X-TOKEN from header param [X-TOKEN] has not yet been implemented")
		},

		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*ExchangeAppAPI Excange core functionality */
type ExchangeAppAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer
	// UrlformConsumer registers a consumer for a "application/x-www-form-urlencoded" mime type
	UrlformConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// AccessTokenAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key X-TOKEN provided in the header
	AccessTokenAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// AssetAssetListHandler sets the operation handler for the asset list operation
	AssetAssetListHandler asset.AssetListHandler
	// TraderCreateNewtraderHandler sets the operation handler for the create newtrader operation
	TraderCreateNewtraderHandler trader.CreateNewtraderHandler
	// OrderProcessOrderHandler sets the operation handler for the process order operation
	OrderProcessOrderHandler order.ProcessOrderHandler
	// TraderTraderPortfolioHandler sets the operation handler for the trader portfolio operation
	TraderTraderPortfolioHandler trader.TraderPortfolioHandler
	// TraderTraderPortfoliosHandler sets the operation handler for the trader portfolios operation
	TraderTraderPortfoliosHandler trader.TraderPortfoliosHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *ExchangeAppAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *ExchangeAppAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *ExchangeAppAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *ExchangeAppAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *ExchangeAppAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *ExchangeAppAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *ExchangeAppAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the ExchangeAppAPI
func (o *ExchangeAppAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.UrlformConsumer == nil {
		unregistered = append(unregistered, "UrlformConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.AccessTokenAuth == nil {
		unregistered = append(unregistered, "XTOKENAuth")
	}

	if o.AssetAssetListHandler == nil {
		unregistered = append(unregistered, "asset.AssetListHandler")
	}

	if o.TraderCreateNewtraderHandler == nil {
		unregistered = append(unregistered, "trader.CreateNewtraderHandler")
	}

	if o.OrderProcessOrderHandler == nil {
		unregistered = append(unregistered, "order.ProcessOrderHandler")
	}

	if o.TraderTraderPortfolioHandler == nil {
		unregistered = append(unregistered, "trader.TraderPortfolioHandler")
	}

	if o.TraderTraderPortfoliosHandler == nil {
		unregistered = append(unregistered, "trader.TraderPortfoliosHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *ExchangeAppAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *ExchangeAppAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	result := make(map[string]runtime.Authenticator)
	for name, scheme := range schemes {
		switch name {

		case "accessToken":

			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.AccessTokenAuth)

		}
	}
	return result

}

// Authorizer returns the registered authorizer
func (o *ExchangeAppAPI) Authorizer() runtime.Authorizer {

	return o.APIAuthorizer

}

// ConsumersFor gets the consumers for the specified media types
func (o *ExchangeAppAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		case "application/x-www-form-urlencoded":
			result["application/x-www-form-urlencoded"] = o.UrlformConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *ExchangeAppAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *ExchangeAppAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the exchange app API
func (o *ExchangeAppAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *ExchangeAppAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/asset/list"] = asset.NewAssetList(o.context, o.AssetAssetListHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/trader/register"] = trader.NewCreateNewtrader(o.context, o.TraderCreateNewtraderHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/order"] = order.NewProcessOrder(o.context, o.OrderProcessOrderHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/trader/portfolio"] = trader.NewTraderPortfolio(o.context, o.TraderTraderPortfolioHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/trader/portfolios"] = trader.NewTraderPortfolios(o.context, o.TraderTraderPortfoliosHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *ExchangeAppAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *ExchangeAppAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *ExchangeAppAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *ExchangeAppAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
