// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Exchange
Excange core functionality

Terms Of Service:

N/A


    Schemes:
      http
    Host: localhost:8181
    BasePath: /v1
    Version: 1.0.0
    License: Mit http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <email@email.com>

    Consumes:
    - application/json
    - application/x-www-form-urlencoded

    Produces:
    - application/json

swagger:meta
*/
package restapi
