// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "exchange/models"
)

// AssetListOKCode is the HTTP code returned for type AssetListOK
const AssetListOKCode int = 200

/*AssetListOK successful operation

swagger:response assetListOK
*/
type AssetListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Assets `json:"body,omitempty"`
}

// NewAssetListOK creates AssetListOK with default headers values
func NewAssetListOK() *AssetListOK {

	return &AssetListOK{}
}

// WithPayload adds the payload to the asset list o k response
func (o *AssetListOK) WithPayload(payload []*models.Assets) *AssetListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the asset list o k response
func (o *AssetListOK) SetPayload(payload []*models.Assets) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AssetListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Assets, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// AssetListNotFoundCode is the HTTP code returned for type AssetListNotFound
const AssetListNotFoundCode int = 404

/*AssetListNotFound Token not found

swagger:response assetListNotFound
*/
type AssetListNotFound struct {
}

// NewAssetListNotFound creates AssetListNotFound with default headers values
func NewAssetListNotFound() *AssetListNotFound {

	return &AssetListNotFound{}
}

// WriteResponse to the client
func (o *AssetListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
