// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AssetListHandlerFunc turns a function with the right signature into a asset list handler
type AssetListHandlerFunc func(AssetListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AssetListHandlerFunc) Handle(params AssetListParams) middleware.Responder {
	return fn(params)
}

// AssetListHandler interface for that can handle valid asset list params
type AssetListHandler interface {
	Handle(AssetListParams) middleware.Responder
}

// NewAssetList creates a new http.Handler for the asset list operation
func NewAssetList(ctx *middleware.Context, handler AssetListHandler) *AssetList {
	return &AssetList{Context: ctx, Handler: handler}
}

/*AssetList swagger:route GET /asset/list asset assetList

List all assets

*/
type AssetList struct {
	Context *middleware.Context
	Handler AssetListHandler
}

func (o *AssetList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAssetListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
