// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Portfolios portfolios
// swagger:model Portfolios
type Portfolios struct {

	// portfolio
	Portfolio Portfolio `json:"portfolio,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this portfolios
func (m *Portfolios) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePortfolio(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Portfolios) validatePortfolio(formats strfmt.Registry) error {

	if swag.IsZero(m.Portfolio) { // not required
		return nil
	}

	if err := m.Portfolio.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("portfolio")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Portfolios) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Portfolios) UnmarshalBinary(b []byte) error {
	var res Portfolios
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
